# Generated by Django 4.0.4 on 2022-06-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('idCuenta', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la cuenta')),
                ('nombreUsuario', models.CharField(max_length=100, verbose_name='Nombre de la cuenta')),
                ('contraUsuario', models.CharField(max_length=100, verbose_name='Contraseña de la cuenta')),
                ('correoUsuario', models.CharField(max_length=200, verbose_name='Correo de la cuenta')),
            ],
        ),
    ]
