# Generated by Django 4.0.4 on 2022-06-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del producto')),
                ('nombreProducto', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('precio', models.IntegerField(max_length=100, verbose_name='Precio del producto')),
                ('direccionCasa', models.CharField(max_length=250, verbose_name='Dirrecion del comprador')),
            ],
        ),
    ]
