# Generated by Django 4.0.4 on 2022-06-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_producto_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('idSuscripcion', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la suscripcion')),
                ('nombreCliente', models.CharField(max_length=250, verbose_name='Nombre del suscriptor')),
            ],
        ),
    ]
